In [2]:
import pandas as pd
import numpy as np

# Afficher toutes les colonnes
pd.set_option('display.max_columns', None)

In [7]:
train = pd.read_csv("train.csv", engine='python')
store = pd.read_csv("store.csv")
test = pd.read_csv("test.csv")

In [8]:
print("Train :", train.shape)
print("Store :", store.shape)
print("Test :", test.shape)

Train : (1017209, 9)
Store : (1115, 10)
Test : (41088, 8)

In [9]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [10]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [11]:
test.head()

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [12]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(2)
memory usage: 69.8+ MB

In [13]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   object
 2   Assortment                 1115 non-null   object
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB

In [14]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41088 entries, 0 to 41087
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             41088 non-null  int64
 1   Store          41088 non-null  int64
 2   DayOfWeek      41088 non-null  int64
 3   Date           41088 non-null  object
 4   Open           41077 non-null  float64
 5   Promo          41088 non-null  int64
 6   StateHoliday   41088 non-null  object
 7   SchoolHoliday  41088 non-null  int64
dtypes: float64(1), int64(5), object(2)
memory usage: 2.5+ MB

In [15]:
train.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00

In [16]:
train.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

In [17]:
store.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [18]:
test.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday'],
      dtype='object')

In [19]:
train.shape

(1017209, 9)

In [20]:
store.shape

(1115, 10)

In [21]:
test.shape

(41088, 8)

In [22]:
train.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [23]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [24]:
test.isnull().sum()

Id                0
Store             0
DayOfWeek         0
Date              0
Open             11
Promo             0
StateHoliday      0
SchoolHoliday     0
dtype: int64

In [25]:
train.duplicated().sum()

np.int64(0)

In [26]:
store.duplicated().sum()

np.int64(0)

In [27]:
test.duplicated().sum()

np.int64(0)

In [28]:
train.dtypes

Store             int64
DayOfWeek         int64
Date             object
Sales             int64
Customers         int64
Open              int64
Promo             int64
StateHoliday     object
SchoolHoliday     int64
dtype: object

In [29]:
store.dtypes

Store                          int64
StoreType                     object
Assortment                    object
CompetitionDistance          float64
CompetitionOpenSinceMonth    float64
CompetitionOpenSinceYear     float64
Promo2                         int64
Promo2SinceWeek              float64
Promo2SinceYear              float64
PromoInterval                 object
dtype: object

In [30]:
test.dtypes

Id                 int64
Store              int64
DayOfWeek          int64
Date              object
Open             float64
Promo              int64
StateHoliday      object
SchoolHoliday      int64
dtype: object

In [31]:
train_clean = train.copy()
store_clean = store.copy()
test_clean = test.copy()

In [32]:
train_clean["Date"] = pd.to_datetime(train_clean["Date"])
store_clean = store_clean.copy()
test_clean["Date"] = pd.to_datetime(test_clean["Date"])

In [33]:
train_clean.dtypes

Store                     int64
DayOfWeek                 int64
Date             datetime64[ns]
Sales                     int64
Customers                 int64
Open                      int64
Promo                     int64
StateHoliday             object
SchoolHoliday             int64
dtype: object

In [34]:
train_clean["Date"].head()

0   2015-07-31
1   2015-07-31
2   2015-07-31
3   2015-07-31
4   2015-07-31
Name: Date, dtype: datetime64[ns]

In [35]:
train_clean.dtypes

Store                     int64
DayOfWeek                 int64
Date             datetime64[ns]
Sales                     int64
Customers                 int64
Open                      int64
Promo                     int64
StateHoliday             object
SchoolHoliday             int64
dtype: object

In [36]:
train_merged = train_clean.merge(
    store_clean,
    on="Store",
    how="left"
)

In [37]:
train_merged.shape

(1017209, 18)

In [38]:
train_merged.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [39]:
train_merged.isnull().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
StoreType                         0
Assortment                        0
CompetitionDistance            2642
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
Promo2                            0
Promo2SinceWeek              508031
Promo2SinceYear              508031
PromoInterval                508031
dtype: int64

In [40]:
median_distance = train_merged["CompetitionDistance"].median()

train_merged["CompetitionDistance"] = train_merged["CompetitionDistance"].fillna(median_distance)

In [42]:
train_merged["CompetitionDistance"].isnull().sum()

np.int64(0)

In [41]:
train_merged["Promo2"].value_counts()

Promo2
1    509178
0    508031
Name: count, dtype: int64

In [43]:
train_merged["Sales"].describe()

count    1.017209e+06
mean     5.773819e+03
std      3.849926e+03
min      0.000000e+00
25%      3.727000e+03
50%      5.744000e+03
75%      7.856000e+03
max      4.155100e+04
Name: Sales, dtype: float64

In [45]:
train_merged[train_merged["Sales"] == 0]["Open"].value_counts()

Open
0    172817
1        54
Name: count, dtype: int64

In [46]:
train_merged["Year"] = train_merged["Date"].dt.year
train_merged["Month"] = train_merged["Date"].dt.month
train_merged["Day"] = train_merged["Date"].dt.day

In [47]:
train_merged[["Date", "Year", "Month", "Day"]].head()

        Date  Year  Month  Day
0 2015-07-31  2015      7   31
1 2015-07-31  2015      7   31
2 2015-07-31  2015      7   31
3 2015-07-31  2015      7   31
4 2015-07-31  2015      7   31

In [48]:
train_merged["WeekOfYear"] = train_merged["Date"].dt.isocalendar().week

In [49]:
train_merged[["Date", "WeekOfYear"]].head()

        Date  WeekOfYear
0 2015-07-31          31
1 2015-07-31          31
2 2015-07-31          31
3 2015-07-31          31
4 2015-07-31          31

In [50]:
train_merged["Quarter"] = train_merged["Date"].dt.quarter

In [51]:
train_merged[["Date", "Quarter"]].head()

        Date  Quarter
0 2015-07-31        3
1 2015-07-31        3
2 2015-07-31        3
3 2015-07-31        3
4 2015-07-31        3

In [52]:
train_merged[["Date", "WeekOfYear", "Quarter"]].head()

        Date  WeekOfYear  Quarter
0 2015-07-31          31        3
1 2015-07-31          31        3
2 2015-07-31          31        3
3 2015-07-31          31        3
4 2015-07-31          31        3

In [53]:
train_merged["IsWeekend"] = train_merged["DayOfWeek"].apply(
    lambda x: 1 if x >= 6 else 0
)

In [54]:
train_merged["DaysSinceStart"] = (
    train_merged["Date"] - train_merged["Date"].min()
).dt.days

In [55]:
train_merged[
    ["Date", "DayOfWeek", "IsWeekend", "DaysSinceStart"]
].head(10)

        Date  DayOfWeek  IsWeekend  DaysSinceStart
0 2015-07-31          5          0             941
1 2015-07-31          5          0             941
2 2015-07-31          5          0             941
3 2015-07-31          5          0             941
4 2015-07-31          5          0             941
5 2015-07-31          5          0             941
6 2015-07-31          5          0             941
7 2015-07-31          5          0             941
8 2015-07-31          5          0             941
9 2015-07-31          5          0             941

In [56]:
train_merged["IsMonthStart"] = train_merged["Date"].dt.is_month_start.astype(int)

train_merged["IsMonthEnd"] = train_merged["Date"].dt.is_month_end.astype(int)

In [57]:
train_merged[
    ["Date", "IsMonthStart", "IsMonthEnd"]
].head(10)

        Date  IsMonthStart  IsMonthEnd
0 2015-07-31             0           1
1 2015-07-31             0           1
2 2015-07-31             0           1
3 2015-07-31             0           1
4 2015-07-31             0           1
5 2015-07-31             0           1
6 2015-07-31             0           1
7 2015-07-31             0           1
8 2015-07-31             0           1
9 2015-07-31             0           1

In [58]:
train_merged["HasPromo2Start"] = train_merged["Promo2SinceYear"].notna().astype(int)

In [59]:
train_merged["HasPromo2Start"].value_counts()

HasPromo2Start
1    509178
0    508031
Name: count, dtype: int64

In [60]:
train_merged["Promo2Age"] = (
    train_merged["Year"] - train_merged["Promo2SinceYear"]
)

train_merged["Promo2Age"] = train_merged["Promo2Age"].fillna(0)

In [61]:
train_merged[["Promo2SinceYear", "Year", "Promo2Age"]].head(10)

   Promo2SinceYear  Year  Promo2Age
0              NaN  2015        0.0
1           2010.0  2015        5.0
2           2011.0  2015        4.0
3              NaN  2015        0.0
4              NaN  2015        0.0
5              NaN  2015        0.0
6              NaN  2015        0.0
7              NaN  2015        0.0
8              NaN  2015        0.0
9              NaN  2015        0.0

In [62]:
train_merged["HasCompetition"] = (
    train_merged["CompetitionOpenSinceYear"]
    .notna()
    .astype(int)
)

In [63]:
train_merged["HasCompetition"].value_counts()

HasCompetition
1    693861
0    323348
Name: count, dtype: int64

In [64]:
train_merged["CompetitionAge"] = (
    train_merged["Year"] - train_merged["CompetitionOpenSinceYear"]
)

train_merged["CompetitionAge"] = train_merged["CompetitionAge"].fillna(0)

In [65]:
train_merged[
    ["CompetitionOpenSinceYear", "Year", "CompetitionAge"]
].head(10)

   CompetitionOpenSinceYear  Year  CompetitionAge
0                    2008.0  2015             7.0
1                    2007.0  2015             8.0
2                    2006.0  2015             9.0
3                    2009.0  2015             6.0
4                    2015.0  2015             0.0
5                    2013.0  2015             2.0
6                    2013.0  2015             2.0
7                    2014.0  2015             1.0
8                    2000.0  2015            15.0
9                    2009.0  2015             6.0

In [66]:
train_merged["StoreType"].value_counts()

StoreType
a    551627
d    312912
c    136840
b     15830
Name: count, dtype: int64

In [67]:
train_merged["Assortment"].value_counts()

Assortment
a    537445
c    471470
b      8294
Name: count, dtype: int64

In [68]:
train_merged["StateHoliday"].value_counts()

StateHoliday
0    986159
a     20260
b      6690
c      4100
Name: count, dtype: int64

In [69]:
train_merged["PromoInterval"].value_counts()

PromoInterval
Jan,Apr,Jul,Oct     293122
Feb,May,Aug,Nov     118596
Mar,Jun,Sept,Dec     97460
Name: count, dtype: int64

In [70]:
train_merged["Date"].min(), train_merged["Date"].max()

(Timestamp('2013-01-01 00:00:00'), Timestamp('2015-07-31 00:00:00'))